import React,{useEffect,useMemo,useState}from'react';import{createRoot}from'react-dom/client';import'./style.css';
const API='http://localhost:4000/api';
function Stars({n=5}){return <span className="stars">{'★'.repeat(Math.round(n))}{'☆'.repeat(5-Math.round(n))}</span>}
function money(n){return '$'+Number(n||0).toFixed(2)}
function App(){const[page,setPage]=useState(location.hash.slice(1)||'home');const[products,setProducts]=useState([]);const[posts,setPosts]=useState([]);const[compare,setCompare]=useState(JSON.parse(localStorage.compare||'[]'));useEffect(()=>{fetch(API+'/products').then(r=>r.json()).then(setProducts);fetch(API+'/blog').then(r=>r.json()).then(setPosts)},[]);useEffect(()=>{localStorage.compare=JSON.stringify(compare)},[compare]);window.onhashchange=()=>setPage(location.hash.slice(1)||'home');const go=p=>{location.hash=p};const cats=[...new Set(products.map(p=>p.category))];const addCompare=p=>setCompare(v=>v.find(x=>x.id===p.id)?v:[...v,p]);return <><Nav go={go} cats={cats}/>{page==='home'&&<Home products={products} go={go} addCompare={addCompare}/>} {page==='best'&&<Best products={products} addCompare={addCompare}/>} {page==='compare'&&<Compare items={compare} setCompare={setCompare}/>} {page.startsWith('product/')&&<Product id={page.split('/')[1]} products={products}/>} {page.startsWith('cat/')&&<Category name={decodeURIComponent(page.split('/')[1])} products={products} addCompare={addCompare}/>} {page==='blog'&&<Blog posts={posts}/>} {page.startsWith('post/')&&<Post slug={page.split('/')[1]} posts={posts}/>} {page==='ai'&&<AI/>} {page==='admin'&&<Admin products={products} posts={posts} setProducts={setProducts} setPosts={setPosts}/>}<Footer go={go}/></>}
function Nav({go,cats}){return <header><b className="logo" onClick={()=>go('home')}>Affilify Ops</b><nav><button onClick={()=>go('home')}>Home</button><button onClick={()=>go('best')}>Best Products</button><button onClick={()=>go('compare')}>Compare</button><button onClick={()=>go('blog')}>Blog</button><button onClick={()=>go('ai')}>AI Employees</button><button onClick={()=>go('admin')}>Admin</button></nav></header>}
function Card({p,addCompare}){return <div className="card"><span className="badge">{p.badge}</span><img src={p.image_url}/><h3>{p.name}</h3><p>{p.short_desc}</p><Stars n={p.rating}/><b>{money(p.price)}</b><div className="row"><a className="btn" href={'#/product/'+p.id}>Review</a><button onClick={()=>addCompare(p)}>Compare</button></div></div>}
function Home({products,go,addCompare}){const[q,setQ]=useState('');const list=products.filter(p=>p.name.toLowerCase().includes(q.toLowerCase()));return <main><section className="hero"><h1>Find the best Amazon products without wasting money.</h1><p>Reviews, comparisons, best-value picks, and buying guides built for affiliate conversion.</p><button onClick={()=>go('best')}>View Best Products</button></section><input className="search" placeholder="Search products..." value={q} onChange={e=>setQ(e.target.value)}/><Grid products={list} addCompare={addCompare}/></main>}
function Grid({products,addCompare}){return <section className="grid">{products.map(p=><Card key={p.id} p={p} addCompare={addCompare}/>)}</section>}
function Best({products,addCompare}){return <main><h1>Best Products</h1><p>Ranked by rating, badge, and value score.</p><Grid products={[...products].sort((a,b)=>b.rating-a.rating||a.price-b.price)} addCompare={addCompare}/></main>}
function Product({id,products}){const p=products.find(x=>String(x.id)===String(id));if(!p)return <main>Loading...</main>;const rel=products.filter(x=>x.category===p.category&&x.id!==p.id).slice(0,3);return <main><section className="product"><img src={p.image_url}/><div><span className="badge">{p.badge}</span><h1>{p.name}</h1><Stars n={p.rating}/><h2>{money(p.price)}</h2><p>{p.full_desc}</p><h3>Why I Recommend This</h3><p>{p.recommendation}</p><div className="cols"><div><h3>Pros</h3><ul>{p.pros.split(',').map(x=><li>{x.trim()}</li>)}</ul></div><div><h3>Cons</h3><ul>{p.cons.split(',').map(x=><li>{x.trim()}</li>)}</ul></div></div><a className="cta" target="_blank" href={API+'/out/'+p.id}>Get Best Price →</a><small>As an affiliate, we may earn a commission if you purchase through our links, at no extra cost to you.</small></div></section><h2>Related Products</h2><Grid products={rel} addCompare={()=>{}}/></main>}
function Category({name,products,addCompare}){const[sort,setSort]=useState('rating');let list=products.filter(p=>p.category===name);if(sort==='low')list.sort((a,b)=>a.price-b.price);if(sort==='high')list.sort((a,b)=>b.price-a.price);if(sort==='rating')list.sort((a,b)=>b.rating-a.rating);return <main><h1>{name}</h1><select onChange={e=>setSort(e.target.value)}><option value="rating">Top rated</option><option value="low">Price low-high</option><option value="high">Price high-low</option></select><Grid products={list} addCompare={addCompare}/></main>}
function Compare({items,setCompare}){const best=[...items].sort((a,b)=>(b.rating/b.price)-(a.rating/a.price))[0];return <main><h1>Product Comparison</h1><p>Pick the best price/value product before sending the buyer to Amazon.</p>{best&&<div className="winner"><b>Best Value:</b> {best.name} at {money(best.price)} <a target="_blank" href={API+'/out/'+best.id}>Buy on Amazon →</a></div>}<div className="table"><table><tbody><tr><th>Feature</th>{items.map(p=><th>{p.name}</th>)}</tr><tr><td>Price</td>{items.map(p=><td>{money(p.price)}</td>)}</tr><tr><td>Rating</td>{items.map(p=><td><Stars n={p.rating}/></td>)}</tr><tr><td>Badge</td>{items.map(p=><td>{p.badge}</td>)}</tr><tr><td>Pros</td>{items.map(p=><td>{p.pros}</td>)}</tr><tr><td>Cons</td>{items.map(p=><td>{p.cons}</td>)}</tr><tr><td>Action</td>{items.map(p=><td><a className="btn" target="_blank" href={API+'/out/'+p.id}>Get Best Price</a></td>)}</tr></tbody></table></div><button onClick={()=>setCompare([])}>Clear Compare</button></main>}
function Blog({posts}){return <main><h1>Buying Guides</h1><section className="grid">{posts.map(p=><a className="card" href={'#/post/'+p.slug}><img src={p.thumbnail}/><h3>{p.title}</h3><p>{p.excerpt}</p><small>{p.created_at}</small></a>)}</section></main>}
function Post({slug,posts}){const p=posts.find(x=>x.slug===slug);return <main><article><h1>{p?.title}</h1><img className="wide" src={p?.thumbnail}/><p>{p?.content}</p></article></main>}
const teams=['CEO','HR','Sales','Coding','Bug Solver','Executive'];function AI(){const[team,setTeam]=useState('CEO'),[input,setInput]=useState('home office gear'),[out,setOut]=useState('');function run(){const report=`## ${team} Report\n\nInput: ${input}\n\n- Goal: sell more Amazon products with reviews, comparisons, and best-value CTAs.\n- Next action: publish one buyer-intent article, add three products, compare pricing, and push users to Amazon through tracked buttons.\n- Reporting: ${team==='CEO'?'CEO report goes to Admin dashboard.':team==='HR'?'HR reports to CEO.':'Employees report to HR and Executive.'}`;setOut(report);localStorage.aiReports=JSON.stringify([...(JSON.parse(localStorage.aiReports||'[]')),report])}return <main><h1>AI Employees Command Center</h1><p>Business automation workspace for the affiliate site.</p><div className="tabs">{teams.map(t=><button onClick={()=>setTeam(t)} className={team===t?'active':''}>{t}</button>)}</div><div className="panel"><h2>AI {team}</h2><textarea value={input} onChange={e=>setInput(e.target.value)}/><textarea value={`You are the AI ${team}. Create a practical Amazon affiliate marketing report. Focus on selling products through search, reviews, comparisons, and best-price CTAs.`} readOnly/><button onClick={run}>Run Team</button><button onClick={()=>navigator.clipboard.writeText(input)}>Copy Prompt</button><button onClick={()=>localStorage.savedOutput=out}>Save Output</button><pre>{out||'Run this team to generate a report.'}</pre></div></main>}
function Admin({products,posts,setProducts,setPosts}){const[pw,setPw]=useState(localStorage.admin||''),[clicks,setClicks]=useState([]);useEffect(()=>{if(pw==='admin123'){localStorage.admin=pw;fetch(API+'/clicks').then(r=>r.json()).then(setClicks)}},[pw]);if(pw!=='admin123')return <main><h1>Admin Login</h1><input type="password" placeholder="admin123" onChange={e=>setPw(e.target.value)}/></main>;const reports=JSON.parse(localStorage.aiReports||'[]');return <main><h1>Admin Operations Dashboard</h1><section className="metrics"><div><b>{products.length}</b><span>Products</span></div><div><b>{posts.length}</b><span>Blog Posts</span></div><div><b>{clicks.length}</b><span>Amazon Clicks</span></div><div><b>$500</b><span>Monthly Goal</span></div></section><section className="org"><h2>Reporting Hierarchy</h2><p><b>CEO</b> reports on this Admin page. <b>HR</b> reports to CEO. <b>Employees</b> report to HR and Executive. <b>Executive</b> reviews performance and revenue growth.</p></section><h2>Saved AI Reports</h2>{reports.map((r,i)=><pre key={i}>{r}</pre>)}<h2>Product Management</h2><p>Add/edit/delete can be expanded from the API. Current build includes seeded products, comparison, redirects, and reporting.</p></main>}
function Footer({go}){return <footer><b>Affilify Ops</b><p>Amazon affiliate product reviews, comparisons, and buying guides.</p><button onClick={()=>go('home')}>Home</button><button onClick={()=>go('blog')}>Blog</button><button onClick={()=>go('best')}>Best Products</button></footer>}
createRoot(document.getElementById('root')).render(<App/>);