const express=require('express');const cors=require('cors');const jwt=require('jsonwebtoken');const {OAuth2Client}=require('google-auth-library');const Database=require('better-sqlite3');
const app=express();app.use(cors());app.use(express.json());const db=new Database('affiliate.db');
const JWT_SECRET=process.env.JWT_SECRET||'dev-secret-change-me';const GOOGLE_CLIENT_ID=process.env.GOOGLE_CLIENT_ID||'YOUR_GOOGLE_CLIENT_ID';const ADMIN_EMAILS=(process.env.ADMIN_EMAILS||'').split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);const googleClient=new OAuth2Client(GOOGLE_CLIENT_ID);
const now=()=>new Date().toISOString();const parse=v=>{try{return JSON.parse(v||'{}')}catch{return {raw:v}}};
function sign(u){return jwt.sign({id:u.id,email:u.email,role:u.role,name:u.name,picture:u.picture},JWT_SECRET,{expiresIn:'7d'})}
function auth(req,res,next){const h=req.headers.authorization||'';const token=h.startsWith('Bearer ')?h.slice(7):null;if(!token)return res.status(401).json({error:'Login required'});try{req.user=jwt.verify(token,JWT_SECRET);next()}catch(e){res.status(401).json({error:'Invalid token'})}}
function admin(req,res,next){if(req.user?.role!=='admin')return res.status(403).json({error:'Admin only'});next()}
function log(userId,type,details={},req=null){db.prepare('INSERT INTO activity_logs(user_id,role,route,type,details,created_at) VALUES(?,?,?,?,?,?)').run(userId||null,details.role||null,details.route||req?.path||'',type,JSON.stringify(details),now())}
function userById(id){return db.prepare('SELECT id,email,name,picture,role,created_at,last_login FROM users WHERE id=?').get(id)}
db.exec(`
CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY,name TEXT,category TEXT,short_desc TEXT,full_desc TEXT,recommendation TEXT,pros TEXT,cons TEXT,price REAL,image_url TEXT,affiliate_url TEXT,rating REAL,badge TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS blog_posts(id INTEGER PRIMARY KEY,title TEXT,slug TEXT,thumbnail TEXT,excerpt TEXT,content TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,email TEXT UNIQUE,name TEXT,picture TEXT,role TEXT DEFAULT 'user',created_at TEXT,last_login TEXT);
CREATE TABLE IF NOT EXISTS clicks(id INTEGER PRIMARY KEY,product_id INTEGER,user_id INTEGER,type TEXT,created_at TEXT);
CREATE TABLE IF NOT EXISTS activity_logs(id INTEGER PRIMARY KEY,user_id INTEGER,role TEXT,route TEXT,type TEXT,details TEXT,created_at TEXT);
CREATE TABLE IF NOT EXISTS employees(id INTEGER PRIMARY KEY,name TEXT,role TEXT,manager TEXT,status TEXT,focus TEXT,workload INTEGER DEFAULT 0,last_report TEXT DEFAULT '',created_at TEXT,updated_at TEXT);
CREATE TABLE IF NOT EXISTS instructions(id INTEGER PRIMARY KEY,directive TEXT,sales_delta TEXT,priority TEXT,target_date TEXT,notes TEXT,status TEXT,created_at TEXT,created_by INTEGER);
CREATE TABLE IF NOT EXISTS tasks(id INTEGER PRIMARY KEY,instruction_id INTEGER,title TEXT,instruction TEXT,owner TEXT,assigned_by TEXT,status TEXT,priority TEXT,due_date TEXT,result TEXT,created_at TEXT,updated_at TEXT,completed_at TEXT);
CREATE TABLE IF NOT EXISTS reports(id INTEGER PRIMARY KEY,instruction_id INTEGER,task_id INTEGER,author TEXT,recipient TEXT,type TEXT,content TEXT,created_at TEXT);
CREATE TABLE IF NOT EXISTS social_queue(id INTEGER PRIMARY KEY,platform TEXT,product TEXT,caption TEXT,owner TEXT,status TEXT,sent_at TEXT,created_at TEXT,updated_at TEXT);
CREATE TABLE IF NOT EXISTS dm_queue(id INTEGER PRIMARY KEY,audience TEXT,message TEXT,owner TEXT,status TEXT,reply_status TEXT,completed_at TEXT,created_at TEXT,updated_at TEXT);
`);
if(!db.prepare('SELECT COUNT(*) c FROM products').get().c){const img='https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=900';const ins=db.prepare('INSERT INTO products(name,category,short_desc,full_desc,recommendation,pros,cons,price,image_url,affiliate_url,rating,badge) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)');[
['Canva Pro','Design Tools','Fast design tool for creators.','Create affiliate banners, pins, thumbnails, and comparison graphics quickly.','Best for non-designers who need fast product creatives.','Easy templates,fast workflow,good exports','Subscription required,limited advanced control',14.99,img,'https://www.amazon.com/',4.8,'Top Pick'],['Adobe Express','Design Tools','Social graphics for affiliate posts.','A strong design tool for creator assets and promotional content.','Good polish for creator teams.','Brand tools,templates,mobile friendly','Learning curve,paid plan useful',9.99,img,'https://www.amazon.com/',4.5,'Best Value'],['Blue Yeti Mic','Content Gear','USB mic for reviews.','Reliable microphone for voiceovers and product reviews.','Improves trust because audio quality matters.','Clear voice,USB setup,strong build','Bulky,needs desk space',99.99,'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=900','https://www.amazon.com/',4.7,'Top Pick'],['Ring Light Kit','Content Gear','Lighting for reviews.','Simple lighting upgrade for product videos.','Best cheap visual upgrade.','Better lighting,cheap,portable','Glare risk,limited range',39.99,'https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=900','https://www.amazon.com/',4.3,'Best Value'],['Notion Plus','Productivity Apps','Workspace for content ops.','Plan keywords, products, updates, and publishing workflows.','Great for an affiliate content machine.','Flexible databases,templates,team workflow','Setup time,can get messy',10,'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=900','https://www.amazon.com/',4.6,'Top Pick'],['Todoist Pro','Productivity Apps','Publishing task manager.','Keeps reviews, updates, and outreach moving.','Strong for execution discipline.','Fast capture,recurring tasks,clean UI','Less flexible than Notion,no content database',5,'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=900','https://www.amazon.com/',4.4,'Best Value'],['Ergonomic Chair','Home Office Gear','Comfort chair for long workdays.','A practical chair for remote workers comparing comfort and price.','High purchase intent product with strong comparison value.','Comfortable,adjustable,high demand','Bulky,price varies',189.99,'https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=900','https://www.amazon.com/',4.6,'Best Overall'],['Standing Desk Converter','Home Office Gear','Budget sit-stand setup.','Affordable sit-stand upgrade without replacing the whole desk.','Good budget pick for home office buyers.','Affordable,portable,easy setup','Limited size,manual adjustment',79.99,'https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=900','https://www.amazon.com/',4.2,'Budget Pick']].forEach(x=>ins.run(...x));}
if(!db.prepare('SELECT COUNT(*) c FROM blog_posts').get().c){const img='https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=900';[['Best Tools for Affiliate Creators','best-tools-affiliate-creators','A guide to creator tools that improve trust and speed.','Pick tools that improve trust, comparison clarity, and CTA strength.'],['How to Compare Products Before Buying','compare-products-before-buying','A framework for choosing best value.','Compare price, rating, use case, pros, cons, warranty, and long-term value.'],['Best Home Office Gear for Remote Workers','best-home-office-gear','Buyer-ready home office picks.','Focus on comfort, productivity, and products with clear purchase intent.']].forEach(p=>db.prepare('INSERT INTO blog_posts(title,slug,thumbnail,excerpt,content) VALUES(?,?,?,?,?)').run(p[0],p[1],img,p[2],p[3]))}
if(!db.prepare('SELECT COUNT(*) c FROM employees').get().c){[['AI CEO','CEO','Admin','Active','Strategy, delegation, reports',0],['AI HR','HR','AI CEO','Active','Execution coordination',0],['AI Sales Team','Sales','AI HR + Executive','Active','CTAs, offers, product copy',0],['AI Coding Team','Coding','AI HR + Executive','Active','Tracking, links, schema, speed',0],['AI Social Team','Social','AI HR + Executive','Active','Social post queue and captions',0],['AI Outreach Team','Outreach','AI HR + Executive','Active','DM scripts and audience outreach',0],['AI Bug Solver','Bug Solver','AI HR + Executive','Active','Rank drops, broken links, issues',0],['AI Executive','Executive','Admin','Active','Analytics and revenue review',0]].forEach(e=>db.prepare('INSERT INTO employees(name,role,manager,status,focus,workload,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').run(...e,now(),now()))}
function upsertUser(p,forceRole){const email=p.email.toLowerCase();let u=db.prepare('SELECT * FROM users WHERE email=?').get(email);const role=forceRole||(ADMIN_EMAILS.includes(email)?'admin':'user');if(u){db.prepare('UPDATE users SET name=?,picture=?,role=?,last_login=? WHERE email=?').run(p.name||u.name,p.picture||u.picture,role,u.role==='admin'?'admin':role,now(),email);u=db.prepare('SELECT * FROM users WHERE email=?').get(email)}else{const r=db.prepare('INSERT INTO users(email,name,picture,role,created_at,last_login) VALUES(?,?,?,?,?,?)').run(email,p.name||email,p.picture||'',role,now(),now());u=userById(r.lastInsertRowid)}log(u.id,'login',{email:u.email,role:u.role,route:'/login'});return u}
app.post('/api/auth/google',async(req,res)=>{try{const{credential}=req.body;const ticket=await googleClient.verifyIdToken({idToken:credential,audience:GOOGLE_CLIENT_ID});const p=ticket.getPayload();const u=upsertUser({email:p.email,name:p.name,picture:p.picture});res.json({token:sign(u),user:u})}catch(e){res.status(401).json({error:'Google login failed',detail:e.message})}});
app.post('/api/auth/dev-login',(req,res)=>{const role=req.body.role==='admin'?'admin':'user';const email=req.body.email||(role==='admin'?'admin@example.com':'user@example.com');const u=upsertUser({email,name:req.body.name||`${role} demo`,picture:''},role);res.json({token:sign(u),user:u})});
app.post('/api/logout',auth,(req,res)=>{log(req.user.id,'logout',{email:req.user.email,role:req.user.role});res.json({ok:true})});
app.get('/api/me',auth,(req,res)=>res.json({user:userById(req.user.id)||req.user}));
app.post('/api/activity',(req,res)=>{log(req.body.user_id,req.body.type||'event',req.body.details||{},req);res.json({ok:true})});
app.get('/api/products',(req,res)=>res.json(db.prepare('SELECT id,name,category,short_desc,full_desc,recommendation,pros,cons,price,image_url,rating,badge,created_at FROM products ORDER BY id DESC').all()));
app.get('/api/products/:id',(req,res)=>{const p=db.prepare('SELECT id,name,category,short_desc,full_desc,recommendation,pros,cons,price,image_url,rating,badge,created_at FROM products WHERE id=?').get(req.params.id);if(!p)return res.status(404).json({error:'Not found'});res.json(p)});
app.get('/api/blog',(req,res)=>res.json(db.prepare('SELECT * FROM blog_posts ORDER BY id DESC').all()));
app.get('/out/:productId',(req,res)=>{const p=db.prepare('SELECT affiliate_url,name FROM products WHERE id=?').get(req.params.productId);if(!p)return res.status(404).send('Product not found');const uid=req.query.user_id||null;db.prepare('INSERT INTO clicks(product_id,user_id,type,created_at) VALUES(?,?,?,?)').run(req.params.productId,uid,'amazon_outbound',now());log(uid,'amazon_click',{product_id:req.params.productId,product:p.name,route:req.path,type:'purchase_intent'});res.redirect(p.affiliate_url)});
app.get('/api/out/:productId',(req,res)=>res.redirect('/out/'+req.params.productId+'?user_id='+(req.query.user_id||'')));
app.get('/api/account/history',auth,(req,res)=>res.json({activity:db.prepare('SELECT * FROM activity_logs WHERE user_id=? ORDER BY id DESC').all(req.user.id).map(a=>({...a,details:parse(a.details)})),clicks:db.prepare('SELECT c.*,p.name product_name FROM clicks c LEFT JOIN products p ON p.id=c.product_id WHERE c.user_id=? ORDER BY c.id DESC').all(req.user.id)}));
app.get('/api/admin/dashboard',auth,admin,(req,res)=>res.json({users:db.prepare('SELECT id,email,name,role,last_login,created_at FROM users ORDER BY last_login DESC').all(),employees:db.prepare('SELECT * FROM employees ORDER BY id').all(),instructions:db.prepare('SELECT * FROM instructions ORDER BY id DESC').all(),tasks:db.prepare('SELECT * FROM tasks ORDER BY id DESC').all(),reports:db.prepare('SELECT * FROM reports ORDER BY id DESC').all(),activity:db.prepare('SELECT a.*,u.email,u.name FROM activity_logs a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.id DESC LIMIT 500').all().map(a=>({...a,details:parse(a.details)})),clicks:db.prepare('SELECT c.*,p.name product_name,u.email FROM clicks c LEFT JOIN products p ON p.id=c.product_id LEFT JOIN users u ON u.id=c.user_id ORDER BY c.id DESC').all(),social:db.prepare('SELECT * FROM social_queue ORDER BY id DESC').all(),dms:db.prepare('SELECT * FROM dm_queue ORDER BY id DESC').all()}));
app.get('/api/admin/users/:id/timeline',auth,admin,(req,res)=>res.json({user:userById(req.params.id),activity:db.prepare('SELECT * FROM activity_logs WHERE user_id=? ORDER BY id DESC').all(req.params.id).map(a=>({...a,details:parse(a.details)})),clicks:db.prepare('SELECT c.*,p.name product_name FROM clicks c LEFT JOIN products p ON p.id=c.product_id WHERE c.user_id=? ORDER BY c.id DESC').all(req.params.id)}));
app.post('/api/admin/employees',auth,admin,(req,res)=>{const b=req.body;const r=db.prepare('INSERT INTO employees(name,role,manager,status,focus,workload,last_report,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').run(b.name,b.role,b.manager,b.status||'Active',b.focus||'',b.workload||0,b.last_report||'',now(),now());log(req.user.id,'employee_add',{employee:b.name,role:req.user.role});res.json({id:r.lastInsertRowid})});
app.put('/api/admin/employees/:id',auth,admin,(req,res)=>{const b=req.body;db.prepare('UPDATE employees SET name=?,role=?,manager=?,status=?,focus=?,workload=?,last_report=?,updated_at=? WHERE id=?').run(b.name,b.role,b.manager,b.status,b.focus,b.workload||0,b.last_report||'',now(),req.params.id);log(req.user.id,'employee_update',{employee_id:req.params.id,role:req.user.role});res.json({ok:true})});
app.delete('/api/admin/employees/:id',auth,admin,(req,res)=>{db.prepare('DELETE FROM employees WHERE id=?').run(req.params.id);log(req.user.id,'employee_delete',{employee_id:req.params.id,role:req.user.role});res.json({ok:true})});
function task(title,instruction,owner,by,priority,due,instructionId=null){const r=db.prepare('INSERT INTO tasks(instruction_id,title,instruction,owner,assigned_by,status,priority,due_date,result,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(instructionId,title,instruction,owner,by,'Assigned',priority,due||'Tomorrow','',now(),now());db.prepare('UPDATE employees SET workload=workload+1,updated_at=? WHERE name=?').run(now(),owner);return r.lastInsertRowid}
function report(instructionId,taskId,author,recipient,type,content){return db.prepare('INSERT INTO reports(instruction_id,task_id,author,recipient,type,content,created_at) VALUES(?,?,?,?,?,?,?)').run(instructionId,taskId,author,recipient,type,content,now()).lastInsertRowid}
app.post('/api/admin/instructions/ceo',auth,admin,(req,res)=>{const b=req.body;const priority=b.priority||((b.sales_delta||'').includes('-')?'High':'Medium');const ir=db.prepare('INSERT INTO instructions(directive,sales_delta,priority,target_date,notes,status,created_at,created_by) VALUES(?,?,?,?,?,?,?,?)').run(b.directive,b.sales_delta||'',priority,b.target_date||'Tomorrow',b.notes||'','Delegated',now(),req.user.id);const id=ir.lastInsertRowid;const negative=(b.sales_delta||'').includes('-');const jobs=[['Sales recovery: CTA and offer rewrite',`Directive: ${b.directive}. Sales update: ${b.sales_delta}. Improve review CTAs, best-value recommendation, and comparison copy.`,'AI Sales Team'],['HR execution coordination',`Coordinate all teams, collect updates, enforce due dates, and report blockers for directive: ${b.directive}`,'AI HR'],['Executive conversion review',`Review traffic, Amazon clicks, compare actions, user intent, and revenue gap. Prepare recovery metrics.`,'AI Executive'],['Tracking and link audit',`Verify /out tracking, Amazon buttons, product review routes, page speed, and event logs.`,'AI Coding Team'],['Social recovery campaign',`Queue social posts for best products and comparison pages. Highlight best value and budget picks.`,'AI Social Team'],['Outreach recovery campaign',`Draft DM outreach for target buyers and creators. Track reply status.`,'AI Outreach Team'],['Bug and ranking diagnosis',`Find broken links, weak pages, ranking drops, and conversion blockers tied to ${b.sales_delta}.`,'AI Bug Solver']];const ids=jobs.map(j=>task(j[0],j[1],j[2],'AI CEO',priority,b.target_date||'Tomorrow',id));if(negative){db.prepare('INSERT INTO social_queue(platform,product,caption,owner,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').run('Instagram','Best Products','Sales dropped today. Push best-value product comparison with urgency CTA.','AI Social Team','Queued',now(),now());db.prepare('INSERT INTO dm_queue(audience,message,owner,status,reply_status,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').run('Warm prospects and remote workers','We found a better-value product option today. Want the quick comparison link?','AI Outreach Team','Drafted','No reply yet',now(),now())}
const content=`CEO Delegation Report\n\nDirective: ${b.directive}\nSales update: ${b.sales_delta||'Not provided'}\nPriority: ${priority}\n\nActions taken:\n- Created ${ids.length} delegated tasks for Sales, HR, Executive, Coding, Social, Outreach, and Bug Solver teams.\n- ${negative?'Sales recovery workflow activated for negative INR delta.':'Standard execution workflow activated.'}\n- Social and outreach coordination ${negative?'queued.':'available if needed.'}\n\nBlockers: Awaiting employee task results.\nTomorrow agenda:\n1. Review completed task reports.\n2. Verify Amazon click movement.\n3. Improve weakest product review CTA.\n4. Publish or update one buyer-intent comparison.\n5. CEO final report after task completion.`;report(id,null,'AI CEO','Admin','CEO Delegation Report',content);log(req.user.id,'ceo_instruction_published',{instruction_id:id,sales_delta:b.sales_delta,role:req.user.role});res.json({instruction_id:id,task_ids:ids,report:content})});
app.post('/api/admin/tasks',auth,admin,(req,res)=>{const b=req.body;const id=task(b.title,b.instruction,b.owner,b.assigned_by||'Admin',b.priority||'Medium',b.due_date||'Tomorrow',b.instruction_id||null);log(req.user.id,'direct_instruction',{task_id:id,owner:b.owner,role:req.user.role});res.json({id})});
app.put('/api/admin/tasks/:id',auth,admin,(req,res)=>{const b=req.body;const old=db.prepare('SELECT * FROM tasks WHERE id=?').get(req.params.id);if(!old)return res.status(404).json({error:'Task not found'});db.prepare('UPDATE tasks SET owner=?,status=?,priority=?,due_date=?,instruction=?,result=?,updated_at=?,completed_at=? WHERE id=?').run(b.owner||old.owner,b.status||old.status,b.priority||old.priority,b.due_date||old.due_date,b.instruction||old.instruction,b.result??old.result,now(),b.status==='Completed'?(old.completed_at||now()):old.completed_at,req.params.id);if(b.status==='Completed'){if(!String(b.result||old.result||'').trim())return res.status(400).json({error:'Completion requires result text'});db.prepare('UPDATE employees SET workload=CASE WHEN workload>0 THEN workload-1 ELSE 0 END,last_report=?,updated_at=? WHERE name=?').run(b.result||old.result,now(),b.owner||old.owner);report(old.instruction_id,old.id,b.owner||old.owner,'AI CEO','Employee Task Report',`Task completed: ${old.title}\nOwner: ${b.owner||old.owner}\nResult: ${b.result||old.result}`);const remaining=db.prepare("SELECT COUNT(*) c FROM tasks WHERE instruction_id=? AND status!='Completed'").get(old.instruction_id).c;if(old.instruction_id&&remaining===0){const instr=db.prepare('SELECT * FROM instructions WHERE id=?').get(old.instruction_id);const completed=db.prepare('SELECT * FROM tasks WHERE instruction_id=?').all(old.instruction_id);const body=`CEO Final Progress Report\n\nDirective: ${instr.directive}\nSales update: ${instr.sales_delta}\n\nActions taken:\n${completed.map(t=>'- '+t.owner+': '+(t.result||t.title)).join('\n')}\n\nBlockers: None reported after all task completions.\nTomorrow agenda:\n- Review Amazon click trend.\n- Double down on best-performing product pages.\n- Refresh weak CTAs.\n- Queue next social/outreach push.\n- Prepare next revenue update.`;report(old.instruction_id,null,'AI CEO','Admin','CEO Final Progress Report',body);db.prepare("UPDATE instructions SET status='Completed' WHERE id=?").run(old.instruction_id)}}log(req.user.id,'task_update',{task_id:req.params.id,status:b.status,role:req.user.role});res.json({ok:true})});
app.post('/api/admin/reports',auth,admin,(req,res)=>{const b=req.body;const id=report(b.instruction_id||null,b.task_id||null,b.author,b.recipient,b.type,b.content);log(req.user.id,'report_create',{report_id:id,role:req.user.role});res.json({id})});
app.post('/api/admin/social',auth,admin,(req,res)=>{const b=req.body;const r=db.prepare('INSERT INTO social_queue(platform,product,caption,owner,status,sent_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').run(b.platform,b.product,b.caption,b.owner,b.status||'Queued',b.sent_at||'',now(),now());log(req.user.id,'social_post_queued',{id:r.lastInsertRowid,platform:b.platform,role:req.user.role});res.json({id:r.lastInsertRowid})});
app.put('/api/admin/social/:id',auth,admin,(req,res)=>{const b=req.body;db.prepare('UPDATE social_queue SET status=?,sent_at=?,updated_at=? WHERE id=?').run(b.status,b.status==='Sent'?(b.sent_at||now()):(b.sent_at||''),now(),req.params.id);log(req.user.id,'social_post_update',{id:req.params.id,status:b.status,role:req.user.role});res.json({ok:true})});
app.post('/api/admin/dms',auth,admin,(req,res)=>{const b=req.body;const r=db.prepare('INSERT INTO dm_queue(audience,message,owner,status,reply_status,completed_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').run(b.audience,b.message,b.owner,b.status||'Drafted',b.reply_status||'No reply yet',b.completed_at||'',now(),now());log(req.user.id,'dm_drafted',{id:r.lastInsertRowid,audience:b.audience,role:req.user.role});res.json({id:r.lastInsertRowid})});
app.put('/api/admin/dms/:id',auth,admin,(req,res)=>{const b=req.body;db.prepare('UPDATE dm_queue SET status=?,reply_status=?,completed_at=?,updated_at=? WHERE id=?').run(b.status,b.reply_status,b.status==='Completed'?(b.completed_at||now()):'',now(),req.params.id);log(req.user.id,'dm_update',{id:req.params.id,status:b.status,role:req.user.role});res.json({ok:true})});
app.listen(4000,()=>console.log('Nexora Commerce AI API running on http://localhost:4000'));